<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Connections" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Connections.Common" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
